### ISSUE TITLE
Conditional Attribute block cannot access `params` after 3.6.0

### ISSUE THREAD

**Issue by copiousfreetime** [okuramasafumi/alba#456]
## Describe the bug

After upgrading to v3.6.0 or later, the following error shows up in my tests.

```
ConditionalAttributesTest#test_conditional_attributes_with_if_with_symbol_method_name:
NameError: undefined local variable or method 'params' for class BlockSerializer
```

```ruby
# Relevant aspects from my codebase
class BlockSerializer < ::ApplicationSerializer
  attribute :links, if: lambda { |object, attr| params[:current_user].admin?  } do |object|
    debugger
    {
      self: "#{params[:api_root]}/blocks/#{object.id}",
      edit: "#{params[:admin_root]}/avo/resources/blocks/#{object.id}/edit"
    }
  end
end
```

## To Reproduce

I have added a new test case demonstrating this behavior change in my fork
- branch <https://github.com/copiousfreetime/alba/tree/conditional-attribute-params-v3.5.0>
- commit <https://github.com/copiousfreetime/alba/commit/6c329a2d4c345df195d146350f0253c7702fdf9d>

Checkout the repo/branch and run `rake test` and it passes

In my v3.6.0 branch, the same test fails
- branch <https://github.com/copiousfreetime/alba/tree/conditional-attribute-params-v3.6.0>
- commit <https://github.com/copiousfreetime/alba/commit/a73349a079f3b7d64293273521c68987d22bf440>

## Expected behavior
I would expect that `params` would be available within the block of an `attribute:` in a Serializer.

## Actual behavior
It appears that sometime between v3.5.0 and v3.6.0 the scope of `params` changed.

## Environment
- Ruby version: 3.4.5

## Additional context

It is quite possible that my original approach on this is an incorrect solution for Albal.  I am open to other solutions to this.

**Comment by copiousfreetime** [comment]
I did another review of the README and it looks like I probably should have used `nested` .. If I change my code to the following - I do not have an error. I'm still not sure if the behavior change between 3.5.0 and 3.6.0 is a bug or not. I have worked around it for the moment.

```ruby
# Relevant aspects from my codebase
class BlockSerializer < ::ApplicationSerializer
  nested :links, if: lambda { |object, attr| params[:current_user].admin?  } do |object|
    attribute :self do
       "#{params[:api_root]}/blocks/#{object.id}"
    end
    attribute :edit do
      "#{params[:admin_root]}/avo/resources/blocks/#{object.id}/edit"
    end
  end
end
```

It may be worth fully documenting the scope of `params` when used with `attribute` and how that interacts with the arity of the `if:` option.

| `attribute with if:` | v3.5.0 `params` available in block | v3.6.0 `params` available in block |
| ------------------ | --------------------------- | - |
| `attribute :links, if: proc { params[:current_user].admin?  } do \|object\| ` | ✅ | ✅ |
| `attribute :links, if: proc { \| _object \| params[:current_user].admin?  } do \|object\| ` | ✅ | ✅ |
| `attribute :links, if: proc { \|_object, _attr\| params[:current_user].admin?  } do \|object\|` | ✅ | ❌ |
